name:                redemption
version:             0.1.0.0
github:              "21-23/redemption"
license:             BSD3
author:              "21/23"
maintainer:          "DaQuirm"
copyright:           "2021 21/23"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/redemption#readme>

default-extensions:
- LambdaCase
- InstanceSigs
- OverloadedStrings
- OverloadedLabels
- NamedFieldPuns
- DeriveGeneric
- DerivingStrategies
- MultiParamTypeClasses
- StandaloneDeriving
- UndecidableInstances
- DataKinds

dependencies:
- base >= 4.7 && < 5
- text
- bytestring
- yaml
- aeson
- time
- containers
- monad-control
- unliftio-core
- uuid
- convertible
- persistent
- persistent-mongoDB
- mongoDB
- template-haskell
- timers
- suspend
- network
- websockets

library:
  source-dirs: src

executables:
  redemption-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redemption

tests:
  redemption-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - redemption
